### ISSUE TITLE
Crash Dump when trying to install Linux M68K (Shatztruhe)

### ISSUE THREAD

**Issue by tomse** [tonioni/WinUAE#115]
Crash dumps from WinUAE v3.3 - apparently v3.4 beta's crashdump has been disabled or cannot write..

Try and install Linux M68K from Shatzthrue
ISO link will be sent on PM on EAB

[Downloads.zip](https://github.com/tonioni/WinUAE/files/511885/Downloads.zip)

**Comment by rofl0r** [comment]
where is the website of this sathzthrue linux m68k ?

**Comment by tomse** [comment]
checking MMU and unchecking JIT pr Toni's instructions fixes the crash.

**Comment by timofonic** [comment]
Why isn't this ISO Open for everyone? Why disabling JIT marks this as solved? Isn't it just a, workaround?

Sorry for questions, but I don't get it. It seems the bug checking process have been extremely behind closed doors and I really fail to understand this so much secrecy.

I want to try Linux M68K. Does it use a recent kernel version? It must be fun!

**Comment by tonioni** [comment]
Linux or (or any other unix-like OS) = MMU emulation is required. JIT is not MMU compatible and also won't like anything too weird, crashes are sometimes normal behavior.

But having matching config and iso would be helpful to see if JIT crash can be worked around.

**Comment by timofonic** [comment]
@tonioni

What's the difficulty of having a JIT emulation with MMU support?

Is this distribution based on newest software or is it legacy?

**Comment by tonioni** [comment]
It would need very large changes to handle address translation and everything else. It would also make it slower. Also, I won't touch JIT code, I won't touch x86 assembly.

**Comment by nekoniaow** [comment]
I guess it would not hurt if WinUAE issued a user facing error message indicating that the emulated code is executing an MMU-requiring instruction while the MMU is disabled because the JIT mode does not support it.
At least this would help users understand that this is not a bug but a consequence of their own setting choice.

An alternative could be to revert to non-JIT mode automatically when encountering instructions not supported by the JIT compiler but this assumes the code is architected to support these kind of dynamic transitions and that might not be the case (I have not looked).
