### ISSUE TITLE
Chip ram kickstart overlay disabled

### ISSUE THREAD

**Issue by michaelortmann** [tonioni/WinUAE#171]
The first write to CIAADDRA in kickstart rom disables chip ram kickstart overlay. Regardless of the value written. I don't have hardware here, but i think it behaves differently. Also writing 0 to CIAAPRA disables it, regardless of the value in CIAADDRA, which seems to be 0 in case of the following demo. i did set uae to a500 model and used fs-uae, but the uae core should be the same.

Demo:
```
; vasmm68k_mot -Fbin overlay.asm -o overlay.rom

CIAAPRA         equ     $bfe001
CIAADDRA        equ     $bfe201

        dc.w    $1111           ; size of kickstart rom=256KB, address=$fc0000
        jmp     $fc0000+main    ; jmp not needed by uae, but address
main                            ; "align 1" needed if not already even address
        ; any of the following 3 instructions disable chip ram kickstart overlay
        move.b #$00,CIAADDRA
        ; move.b #$03,CIAADDRA
        ; move.b #$00,CIAAPRA
death
        jmp death
        ; activate uae debugger and dump memory at $0
```

**Comment by tonioni** [comment]
You probably have Gayle based hardware configured where Gayle handles the overlay (ROM overlay enables at reset, any CIA-A write access disables it). CIA is not needed, CIA pin is not even connected. CD32 reuses unused CIA ROM overlay pin as a CD audio mute.

Advanced chipset panel has ROM overlay mode option.

**Comment by michaelortmann** [comment]
So, i can also expect this behaviour (gayle is documented, but i didn't know about this piece until now) also on real hardware and uae is fine. I Guess this Issue can be closed then. Sry. Can i discuss such issues on irc/freenode somewhere before i open such Issues on GH? Can you name a better dicussion channel? Ive got other questions also, like why my simple keyboard handler works, when i expected much more trouble with timing / latency and such. Btw: fs-uae doesn't have such advanced chipset panel, maybe i should try the "real" winuae.

**Comment by tonioni** [comment]
I don't know what parts of winuae is used in fs-uae and I can't trust anything that fs-uae  does because afaik there is no way to be sure whats the exact UAE config in use.  If you want better answers, run winuae in wine if you don't use windows.

Sorry but I don't really like real-time communication, two usual choices are eab or email.

I don't remember but I am quite sure it was confirmed that it is CIA-A access that disables rom overlay. It also would be most compatible with "normal" method (but Commodore did lots of weird decisions so..). Testing will be quite annoying without in-circuit programmable flash ROM replacements..

What do you mean by CD32 not setting SP? No KS ROM uses initial SP (first 2 words of ROM are always identifier + JMP opcode). I don't think there are any documentation but there isn't anything special, simply disassembling start of ROM should answer most questions.

**Comment by FrodeSolheim** [comment]
FS-UAE writes `debug.uae` to the Logs directory, which contains the resulting UAE config after FS-UAE options and override uae options have been applied.

(Of course, before filing issues with the WinUAE project, I would also recommend to at least reproducing issues with WinUAE first. If issues experienced in FS-UAE cannot be reproduced with WinUAE, bugs should be filed with the FS-UAE project instead).

**Comment by michaelortmann** [comment]
(Yes, no ks rom uses initial ip, but the one i just wrote;)

Under winuae, Adv. Chipset, CIA ROM Overlay enables/disables "any write to CIAA disables overlay". fine.

But: Any write to $BFE001, which is only one address of CIAA, disables it, regardless of that setting. Esp. writing 0x00, which does not change the register content. I still don't trust real hardware doing the same.

**Comment by tonioni** [comment]
I confirmed that any write (any data, any size) from $bfe000 to $bfefff disables ROM overlay on A1200. Any other address or read won't disable it.

$bfe001 zero write disabling overlay without also setting data direction was a bug in UAE, pullup when CIA register is in input mode was missing (Unknown reason. Keyboard led and all floppy bits and others handled it correctly)
