### ISSUE TITLE
Copper timings differ from real A500

### ISSUE THREAD

**Issue by mankeli** [tonioni/WinUAE#188]
Copper move timings don't seem to match real machine. In this case it's an OCS A500 with 512/512 memory, without fat agnus, 1.2 kickstart. (not sure which hw specs are relevant here)

In the [repro bootclock program](https://lerppu.net/markus68k-secret/gettothacopper.adf), a copperlist is created that sets 5 bitplanes, and then runs several loops to adjust bitplane modulos to stretch graphics 2x in y direction. (first loop to line $80, second to $FF and then third until copper is restarted)

bplcon0 is set again every few frames to enable various amount of bitplanes. (every bar is on different bitplane) When there are 4 bitplanes active, the fourth bitplane's final line gets stretched indefinitely during the last copper loop. When the 5th bitplane is enabled, the stretching works properly.

![image](https://user-images.githubusercontent.com/1931915/104885532-da620c00-5970-11eb-941a-fc8122b3d5cb.png)

All other bitplanes work properly~, even though the register to set modulos should affect all even or odd bitplanes~. EDIT: just saw that bitplane modulos are added during their last dma fetch, so this is definitely a timing issue.

EDIT2: There's also mentions elsewhere to differing copper timings, such as https://github.com/AxisOxy/Planet-Rocklobster/blob/3eba7836b18aca13ddbf2c9b579ba926d0aa8b86/readme.txt#L309

**Comment by tonioni** [comment]
Yeah, there are some edge cases that need fixing but I haven't really wanted to do until I have time to do complete overhaul of copper emulation. It is based on few wrong assumptions (which are finally known to be wrong because Alice schematics become available few months ago. Blitter logic was recently updated to match schematics, this mainly affected bad programs that poke BLTCON0 channel enable bits when blitter is already running.) which makes simple fixes very complex.

btw, could you create "better" test program?
1) stop floppy disk motor (or at least allow disk eject). Or preferably, tiny exe (that also runs under KS 1.3)
2) static screen that shows the "bad" bar (=4 or 5 bars visible at startup, then mouse or joystick button can be used to change number of bars). This makes it easier to use for testing and debugging.

**Comment by tonioni** [comment]
This also got fixed almost automatically after custom chipset rewrite, logic is now based on "leaked" chip schematics. First public beta coming soon..
