### ISSUE TITLE
When using Virtual Mouse Driver, the cursor can't move to the top and left edge

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#190]
Hi Toni,

I was trying to figure out a glitch in Amiberry, so I thought I'd test the same thing in WinUAE to see what the behavior is like there. I discovered that it's identical, so I'm reporting this to you in case you're not aware of it:

When using the Virtual Mouse Driver, the pointer works fine in PAL:HighRes mode, but there are problems moving it to the top and left edges if using a PAL:HighRes Laced one.

An example to recreate this is Lightwave, which also uses Overscan (so it utilizes the edges of the screen).
If I use the Virtual Mouse Driver, the pointer cannot be moved further LEFT or UP than shown in this screenshot:
![image](https://user-images.githubusercontent.com/3877365/106032644-05ff9780-60d1-11eb-90be-981b177cdb1d.png)

Beyond those edges, the mouse is released if using Magic Mouse.

Switching the Virtual Mouse Driver off, I can move the pointer all the way to the edges as expected:
![image](https://user-images.githubusercontent.com/3877365/106032811-3c3d1700-60d1-11eb-8725-4827aa685f22.png)

In both cases, the PAL:HighRes mode works normally:
![image](https://user-images.githubusercontent.com/3877365/106032936-668ed480-60d1-11eb-8ec8-65507b4e5a62.png)

Is this an issue you're aware of?

**Comment by tonioni** [comment]
I don't think there is anything WinUAE can do. Virtual mouse simulates drawing tablet which sends absolute coordinates from 0 to whatever is the size of display and the rest is KS ROM input.device's (which natively supports tablet) task to convert to screen coordinates.  Most likely cause is Lightwave does some tricks to create this (overscanned?) mode without actually using system overscan support.

It would be different problem if only right/bottom edges are unreachable because it would mean table coordinate range would have been too small.

**Comment by midwan** [comment]
Thanks for the confirmation - I suspected as such, but I wasn't 100% sure.
Since I've only noticed this in LW so far, I would have to assume it's something specific to that application also.
Closing this as I'm not sure there's anything that can be done for now.
