### ISSUE TITLE
Custom.cpp fails to compile if DEBUGGER is not defined

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#198]
With the recent commits, I believe you have a small mistake:
- custom.cpp, lines 8208 - 8218
```
#ifdef DEBUGGER
		if (dmal_ce) {
			if (debug_dma) {
				record_dma_read_value(dat);
			}
			if (memwatch_enabled) {
				debug_getpeekdma_value(dat);
			}
#endif
		}
		last_custom_value1 = last_custom_value2 = dat;
```

- If DEBUGGER is not defined, this will fail to compile because the closing bracket is outside the #if...#endif block.
- Instead, this should be changed to the following:

```
#ifdef DEBUGGER
		if (dmal_ce) {
			if (debug_dma) {
				record_dma_read_value(dat);
			}
			if (memwatch_enabled) {
				debug_getpeekdma_value(dat);
			}
		}
#endif
		last_custom_value1 = last_custom_value2 = dat;
```
I guess this is what you wanted to achieve in the first place?

**Comment by tonioni** [comment]
Yes, it is still work in progress. But do not use it.

It now mostly works since yesterday but it can be really slow because SPEEDUP is disabled and isn't compatible with new emulation code = custom emulation always runs in cycle-by-cycle mode. This is currently the last missing piece before next official beta.
