### ISSUE TITLE
Strange result when writing directly into BLT0DAT

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#207]
While debugging issue https://github.com/dirkwhoffmann/vAmiga/issues/609 in vAmiga, I’ve written four test cases that utilise the Copper to write directly into BPL0DAT with varying combinations in BPLCON1. Directly after writing to BPL0DAT, the number of enabled bitplanes is modified (I did this to get a better understanding of the shift register logic in Denise).

I.e., the tests consist of several Copper blocks similar to this one:

    dc.w    $4A39, $FFFE
    dc.w    BPLCON1,<some value>
    dc.w    BPLCON0<some value>
    dc.w    NOOP,0
    dc.w    NOOP,0
    dc.w    BPL0DAT,<some value>
    dc.w    BPLCON0,<some value>

In WinUAE 4.9.0, I get the following result (ECS Agnus, OCS Denise):

<img width="719" alt="Bildschirmfoto 2022-01-03 um 20 08 32" src="https://user-images.githubusercontent.com/12561945/147971150-c5838f8c-c96d-4d09-a7f2-27b0d53c09d9.png">
<img width="719" alt="Bildschirmfoto 2022-01-03 um 20 09 03" src="https://user-images.githubusercontent.com/12561945/147971155-af57caf1-fa49-4bda-97f7-820548a5e6c8.png">
<img width="719" alt="Bildschirmfoto 2022-01-03 um 20 09 42" src="https://user-images.githubusercontent.com/12561945/147971160-31775517-b6ae-4be3-a4d3-840e655b4583.png">
<img width="719" alt="Bildschirmfoto 2022-01-03 um 20 10 11" src="https://user-images.githubusercontent.com/12561945/147971164-ca9ec845-db89-4cde-a303-79b55078ed97.png">

On my real machine (and now in vAmiga), it looks like this:

![bpl0dat1_A500_8A](https://user-images.githubusercontent.com/12561945/147971208-d3cbafcb-d156-4b42-81d7-cb3788173fc6.jpg)
![bpl0dat2_A500_8A](https://user-images.githubusercontent.com/12561945/147971222-415c5242-c25d-488d-a277-1a1647379665.jpg)
![bpl0dat3_A500_8A](https://user-images.githubusercontent.com/12561945/147971238-cf3dd624-2b53-4221-8eb3-4d6865e78e4d.jpg)
![bpl0dat4_A500_8A](https://user-images.githubusercontent.com/12561945/147971270-03b10abe-a178-42c5-97e1-f956351e8a0a.jpg)

The test cases (ADFs and sources) are located in the vAmigaTS repo:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPL0DAT

**Comment by tonioni** [comment]
4.9.1 already had some fixes (noticed when testing how sprite behaves when BPL1DAT write disables border which is slightly different on all chipset versions. This behavior at least is identical on all HW, OCS Denise, ECS Denise and AGA tested)

It is almost correct after making sure highest bitplane value is used in second pass of display emulation (instead of using number of planes at the start of line..)

But there is still something wrong:

![image](https://user-images.githubusercontent.com/178454/148375106-7adba542-57c6-4bda-9cfd-c05487294e3d.png)

Internal shifter logic probably has off by one bug somewhere or something.

btw, I still would like to have tiny executables.

**Comment by tonioni** [comment]
Success :)

![image](https://user-images.githubusercontent.com/178454/148423557-fdde580d-14a8-42ae-8882-90462237e672.png)

This needs to be documented but I am not 100% sure how it is working :)
