### ISSUE TITLE
Executing code in color registers does not work (minor issue)

### ISSUE THREAD

**Issue by piru** [tonioni/WinUAE#296]
It seems that the CPU emulation fails to execute code at custom registers (0xdff180 -> in specific). Making the color registers readable (by setting RDRAM in BPLCON2 ) and reading them works fine, but executing code from them appears to just lock the emulation.

This definitely is a low priority issue, and does not need to be fixed anytime soon. I just wanted to report it as part of my 30 year old quest of finding out if this was possible at all. Test application source code is here: https://sintonen.fi/src/colexec/colexec.asm

Background story for this silliness is here: https://infosec.exchange/@harrysintonen/112094698326770395

**Comment by tonioni** [comment]
It probably works if CPU is 68000 or 68010 (+AGA). 68020 programs are assumed not to do too really weird things and also to allow easier debugging (instant halt instead of weird things happening) and custom instruction fetches are redirected to "dummy" accesses. 

Now allowed if 68020+ and more compatible ticked.
