### ISSUE TITLE
SUPERPLUS screenmode loses first line (1 pixel)

### ISSUE THREAD

**Issue by simolg** [tonioni/WinUAE#298]
With screenmode SUPERPLUS (high_res) the first line of the screen is hidden
same problem configuring display: oversan / overscan+ / extreme
. . . dragging the screen down one pixel seems OK

![Capture_01](https://github.com/tonioni/WinUAE/assets/103586111/08936c87-a13e-462a-8e17-382ba06afa03)

Enabling "ultra extreme debug" you see the first hidden line (upper dashed line)

![Capture_04](https://github.com/tonioni/WinUAE/assets/103586111/8db8cffb-7e4a-4408-8f8d-6af5c68e7e8f)

My WinUAE 5.2.0 configuration is FullECS chipset (A600 specs), display line mode = double

Am I configuring something wrong? or is it a bug?
thanks for developing WinUAE ;)

**Comment by tonioni** [comment]
It is a bug. Or more like incorrectly implemented undocumented ECS blanking feature because this behavior depends on how the mode is programmed (Is it CSYNC compatible or requires VGA like HV sync cable. AGA does not have this problem.).  It probably was visible in some older version but that was only accidental.

Fixed in next version.
